Fix header manipulation to Custom Endpoints
logzio/logzio_terraform_client pull request #76
Opened 2021-05-01 16:05 UTC by brunopaiuca

Neither all the Custom endpoints have header definition which means that
the provider expected use the values in the header to set headerMap
causing TERRAFORM CRASH when terraform tried to check the current state
of endpoints already existents.

To work around it in the previous version we were forced to set faked
headers to avoid "Out of index error" and this handling purpose to avoid
this inconvenience.

2021-05-01 16:17 UTC, brunopaiuca commented
I can run the tests successfully using my account credentials. I could see messages related with the environment LOGZIO_API_TOKEN, I am just not sure if the CI environment it correctly configured at this moment. May you help me?

2021-05-03 18:58 UTC, Doron-Bargo commented
Hi @mirii1994 can you work with @brunopaiuca on this PR?

Thanks

2021-05-04 13:37 UTC, mirii1994 commented
Hi @brunopaiuca thanks for your contribution!
I'll check what I can do about the CI configuration, and let you know once it's done :)

2021-05-07 17:54 UTC, brunopaiuca commented
> Hi @brunopaiuca thanks for your contribution!
> I'll check what I can do about the CI configuration, and let you know once it's done :)

Hey Mirii1994, do you know if this changes make sense? We have been using some tricks to make our module works.

2021-05-09 13:07 UTC, mirii1994 requested changes
If I understand correctly, this PR is for when you don't need to add any headers, right?
If so, then it will be better to check if the `headerString` param is empty or not, rather than the condition that's inside the loop.
On a side note, in order to make these changes work, there's a need for further changes in our provider repo, since currently the header parameter is required.

2021-06-07 09:30 UTC, mirii1994 commented
@brunopaiuca to fix this issue, we need to make changes in both our client repo, and our provider repo.
For this repo - PR #80 handles the issue.
We've created a [PR in the provider repo](https://github.com/logzio/terraform-provider-logzio/pull/76), and once it's approved & merged the new provider version will fix this issue.
I'll ping you as soon as we release the new version.

2021-06-07 12:56 UTC, mirii1994 commented
@brunopaiuca Logzio Terraform Provider v1.2.3 is out and handles this issue.
Please use the latest version, and let us know if your issue is solved :)

2021-06-16 08:23 UTC, mirii1994 commented
Closing this PR as this issue was fixed in #80 :)

2021-06-16 08:23 UTC, closed without merging